#!/usr/bin/env node
/**
 * Build the browser half into the artifact the DSH client module system serves.
 *
 *   node scripts/build-client.mjs
 *
 * DSH loads a client plugin from `exports["./client"]`, whose file must be a
 * closure-factory script: it calls `window.__ModuleLoader__.load({id, factory})`
 * and its factory body receives the module-table `require`. That format is
 * normally emitted by the monorepo's tsdown preset, which is unavailable to an
 * out-of-tree plugin and would demand a full checkout build.
 *
 * This script reproduces the exact wrapper the preset emits (banner + intro +
 * footer) around `src/client.js`, so the browser half stays hand-maintainable
 * with no build toolchain. The TSX-free source is deliberate: the artifact must
 * be reproducible from plain JavaScript.
 *
 * What it validates, because each is a silent failure in the browser:
 * - the source contains no backtick, which keeps the emitted artifact inside a
 *   plain double-quoted string surface the wrap can carry verbatim (so the
 *   browser half is written with string concatenation, and names in prose use
 *   quotes rather than code spans);
 * - the source names the id placeholder exactly once.
 */

import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { basename, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const SOURCE = join(ROOT, 'src', 'client.js')
const OUTPUT = join(ROOT, 'lib', 'client.js')
const PLACEHOLDER = '__PLUGIN_ID__'

/** Placeholder the build replaces with the build instant. */
const STAMP_PLACEHOLDER = '__BUILD_STAMP__'

/**
 * Read the package name the bundle must register under.
 * @returns {string} the `name` field of this package's manifest.
 */
function packageName() {
  const manifest = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'))
  if (typeof manifest.name !== 'string' || manifest.name.length === 0) {
    throw new Error('build-client: package.json has no name')
  }
  return manifest.name
}

/**
 * Lower the browser module's ESM exports into plain declarations.
 *
 * Only declaration forms are supported. Each is rewritten in place so the name
 * is bound before the wrapper publishes it, which is what keeps the artifact
 * free of a bundler while still letting src/client.js read as a normal module.
 *
 * @param {string} source - the browser source text.
 * @returns {string} the source with export keywords removed.
 * @throws {Error} when an unsupported export form appears.
 */
function lowerExports(source) {
  if (/^\s*export\s+default\b/m.test(source)) {
    throw new Error('build-client: src/client.js must not use "export default"')
  }
  if (/^\s*export\s*\{/m.test(source)) {
    throw new Error('build-client: src/client.js must not use an export list; export at the declaration')
  }
  return source.replace(
    /^(\s*)export\s+(const|let|var|function|class)\s+([A-Za-z_$][\w$]*)/gm,
    (match, indent, kind, name) => `${indent}${kind} ${name}`,
  )
}

/**
 * Collect the names the source exports, in declaration order.
 * @param {string} source - the browser source text.
 * @returns {string[]} exported binding names.
 */
function exportedNames(source) {
  const names = []
  const pattern = /^\s*export\s+(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*)/gm
  let match
  while ((match = pattern.exec(source)) !== null) names.push(match[1])
  return names
}

/**
 * Wrap the browser source in the closure-factory registration.
 * @param {string} id - the package name (graph row key).
 * @param {string} source - the browser source text.
 * @returns {string} the complete client artifact.
 */
function wrap(id, source) {
  const names = exportedNames(source)
  const lowered = lowerExports(source)
  const published = names.map(name => `\t\texports.${name} = ${name};`)
  const body = lowered
    .split('\n')
    .map(line => (line === '' ? '' : `\t${line}`))
    .join('\n')
  return [
    '// Generated by scripts/build-client.mjs. Edit src/client.js instead.',
    'window.__ModuleLoader__.load({',
    `\tid: ${JSON.stringify(id)},`,
    '\tfactory: (require) => {',
    '\t\tvar module = { exports: {} };',
    '\t\tvar exports = module.exports;',
    '\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });',
    body,
    '',
    ...published,
    '\t\treturn module.exports;',
    '\t},',
    '});',
    '',
  ].join('\n')
}

/**
 * Verify the source can be carried into the wrapper verbatim.
 * @param {string} source - the browser source text.
 * @param {string} id - the package name.
 * @returns {void}
 * @throws {Error} when a construct the wrapper cannot carry is present.
 */
function validate(source, id) {
  const occurrences = source.split(PLACEHOLDER).length - 1
  if (occurrences !== 1) {
    throw new Error(`build-client: src/client.js must use ${PLACEHOLDER} exactly once, found ${occurrences}`)
  }
  const stampOccurrences = source.split(STAMP_PLACEHOLDER).length - 1
  if (stampOccurrences !== 1) {
    throw new Error(`build-client: src/client.js must use ${STAMP_PLACEHOLDER} exactly once, found ${stampOccurrences}`)
  }
  if (source.includes('`')) {
    throw new Error('build-client: src/client.js must not use backticks (use quotes/concat in prose and code)')
  }
  if (source.includes('\r')) {
    throw new Error('build-client: src/client.js must use LF line endings')
  }
  if (id === PLACEHOLDER) throw new Error('build-client: package name equals the placeholder')
}

const id = packageName()
const source = readFileSync(SOURCE, 'utf8').replaceAll('\r\n', '\n')
validate(source, id)
mkdirSync(dirname(OUTPUT), { recursive: true })

/**
 * Derive the build stamp from everything that shapes the artifact.
 *
 * Deliberately NOT a timestamp. A timestamp changes on every run, so a
 * committed artifact would always look modified after a rebuild (noisy diffs)
 * and no check could tell a stale artifact from a fresh one. A content digest
 * is stable when the inputs are, which is what lets `--check` mean something —
 * and it still answers "which revision is this page running?" from the DOM or
 * the console, which is what the stamp exists for.
 *
 * @param {string} sourceText - the validated browser source.
 * @returns {string} a short digest over the source and this build script.
 */
function contentStamp(sourceText) {
  const digest = createHash('sha256')
  digest.update('dsh-peak-guard/client\0')
  digest.update(sourceText)
  digest.update('\0')
  // The build script is an input too: changing the wrapper changes the artifact.
  digest.update(readFileSync(fileURLToPath(import.meta.url)))
  return digest.digest('hex').slice(0, 12)
}

const stamp = contentStamp(source)
const artifact = wrap(id, source.replace(PLACEHOLDER, id).replace(STAMP_PLACEHOLDER, stamp))

// `--check` is CI's question: "is the committed artifact current?" A
// content-derived stamp is what makes that answerable, since a timestamp would
// differ on every run no matter how stale the artifact was.
if (process.argv.includes('--check')) {
  const current = existsSync(OUTPUT) ? readFileSync(OUTPUT, 'utf8') : undefined
  if (current === artifact) {
    process.stdout.write(`build-client: ${basename(OUTPUT)} is up to date (stamp ${stamp})\n`)
  } else {
    process.stderr.write(
      `build-client: ${basename(OUTPUT)} is STALE (expected stamp ${stamp});`
      + ' run `npm run build:client` and commit the result\n',
    )
    process.exitCode = 1
  }
} else {
  writeFileSync(OUTPUT, artifact)
  process.stdout.write(`build-client: wrote ${basename(OUTPUT)} for ${id} (stamp ${stamp})\n`)
}
